---
- name: Deploy Calculator Docker Container
  hosts: all
  connection: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure Docker is installed
      package:
        name: docker.io
        state: present

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: nikayz/scientific-calculator
        source: pull
        tag: "1.0"
    # - name: Running container
    #   shell: docker run -it -d --name calculator nikayz/scientific-calculator:1.0
    - name: Run Calculator container
      community.docker.docker_container:
        name: calculator
        image: nikayz/scientific-calculator:1.0
        state: started

    - name: Run Calculator container with piped inputs
      shell: |
        docker run nikayz/scientific-calculator:1.0 \
        /bin/bash -c "echo -e '1\n16\n2\n5\n4\n2\n3\n5\n' | java -jar target/CalculatorProject-1.0-SNAPSHOT.jar"
